### ISSUE TITLE
Monkey D Luffy falun gong

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/chat#2]
Continuing https://twitter.com/monkey1101luffy/status/590985006425640961

**Comment by monkey1101luffy** [comment]
Hi, nice place for a discussion.

**Comment by cirosantilli** [comment]
~~

> If you think China gov id a dictator gov, I have no prob /w it. I as a Chinese, like most of us, are expecting politic reform

Can you expand on that a bit? You feel your friends in general expect political reform? What kind of reform? Democracy?

**Comment by cirosantilli** [comment]
I also tried http://skeptics.stackexchange.com/questions/27431/is-falun-gong-worse-for-its-practitioners-and-society-than-other-religions-like but it got closed, we could split it claim by claim later.

**Comment by monkey1101luffy** [comment]
Before we continue, I apologize I signed up some new account to discuss with you in anonymous.

**Comment by cirosantilli** [comment]
No problem. Because you are afraid of the government?

**Comment by monkey1101luffy** [comment]
No, I am not afraid, I am afraid of you actually.

**Comment by monkey1101luffy** [comment]
Being anonymous is just so common in many occasions, to keep both of us good privacy.

**Comment by cirosantilli** [comment]
Ha why are you afraid of me? :-)

**Comment by monkey1101luffy** [comment]
By saying this, I mean, I do not like to let you know much of me, and therefore we could be friendly to each other. Right? I barely know you, I need space here in case you are aggressive.

**Comment by monkey1101luffy** [comment]
I definitely hope we are both rational and polite to each other, and could keep our discussion on a good level

**Comment by monkey1101luffy** [comment]
Cool?

**Comment by cirosantilli** [comment]
I understand :-) I think I'm not too aggressive. No worries.

**Comment by cirosantilli** [comment]
I propose we start with: https://github.com/cirosantilli/chat/issues/2#issuecomment-95336832

**Comment by monkey1101luffy** [comment]
Regarding your question. I have to say I am just a student from China. My peers are all well-educated, from top cities and most developed areas in China. And we all came studying abroad since post-high school edu.

**Comment by monkey1101luffy** [comment]
I am not aware of how much you know your girlfriend and how much you have learn from you girlfriend about China. or on your own.

**Comment by cirosantilli** [comment]
5 years together. She told me many things, I I have read a bit on wikipedia. Of course, I take into consideration that she may be biased by falun gong.

**Comment by cirosantilli** [comment]
But my impression of the comunists is bad, like for many people from outside.

**Comment by monkey1101luffy** [comment]
But here is what I have heard and saw: I and my peers, when in high school, always criticize the gov. So did we during the first two years I was in college.

**Comment by monkey1101luffy** [comment]
However when I came to North America, I only found one thing, those who survive are always fierce, strong, and controlled the world, just like the USA, and the old-days UK.

**Comment by monkey1101luffy** [comment]
China has 5+ times the population of the US, but 10% or less the avg wealth of each family.

**Comment by monkey1101luffy** [comment]
That is why we should only concentrate on how to feed everyone in China, how to make our people living a just-so-so life in China

**Comment by cirosantilli** [comment]
> China has 5+ times the population of the US, but 10% or less the avg wealth of each family.

Not sure I follow. This is a good point about the US no?

**Comment by monkey1101luffy** [comment]
In the 1949-1976, the ear our parents grew, everybody in China are fighting for a living. We are the poorest, parents would tell their children, like me, that they can only eat meat once a year in the Chinese new year holiday.

**Comment by monkey1101luffy** [comment]
I compare the condition with the US because its the only country with large territory and population.

**Comment by cirosantilli** [comment]
OK. What point to do you want to make?

**Comment by monkey1101luffy** [comment]
When I was young, my family lived together with my uncle's family and grand parents, in a 60m2(700 sqft) apt unit. The total income of my family is around 1000 USD/yr. Look what China is like today.

**Comment by monkey1101luffy** [comment]
The only point here is, the most people in China, if not everyone, care more about the life, the economy, than the politics

**Comment by cirosantilli** [comment]
I agree. Cary on.

**Comment by monkey1101luffy** [comment]
Because we are poor, for too long time, and no other country would like to really help us. The only thing we can do is to fight on our own.

**Comment by monkey1101luffy** [comment]
However for nowadays, China is becoming better and many people are becoming middle-class.

**Comment by monkey1101luffy** [comment]
They start to think about things that haven been forgotten for the past decades. That is politics.

**Comment by cirosantilli** [comment]
I agree so far. So do you think that people will soon ask for democracy?

**Comment by cirosantilli** [comment]
And wouldn't China be even richer if it were a democracy?

**Comment by monkey1101luffy** [comment]
This is also true with many other country, like the US in the second war,  Roosevelt  was the president for March 4, 1933 – April 12, 1945.

**Comment by monkey1101luffy** [comment]
Democracy is not necessary related to if a country is rich or poor.

**Comment by cirosantilli** [comment]
True, it is hard to correlate.

**Comment by cirosantilli** [comment]
So why not let people have freedom of speech?

**Comment by monkey1101luffy** [comment]
Why do you think there is no freedom of speech in China?

**Comment by monkey1101luffy** [comment]
or limited freedom WHICH is much worse than in the US or else?

**Comment by monkey1101luffy** [comment]
I personally cannot agree.

**Comment by monkey1101luffy** [comment]
I can see anything in China, in my home, in school, in public area

**Comment by monkey1101luffy** [comment]
sorry, say

**Comment by monkey1101luffy** [comment]
only one thing is forbidden in China, that is to harm the society's stable

**Comment by monkey1101luffy** [comment]
this is also true in anywhere else in the world

**Comment by monkey1101luffy** [comment]
But things are a little bit complicated here in China, because, we only have one unique politic party

**Comment by cirosantilli** [comment]
The question is: what if the party does something bad.

**Comment by cirosantilli** [comment]
Then no on can say anything about it. Won't it continue for longer?

**Comment by monkey1101luffy** [comment]
Ha, your smart, that's a great question

**Comment by monkey1101luffy** [comment]
China has nearly 4000 year history

**Comment by monkey1101luffy** [comment]
people witnessed the rise and fall of tens of dynasties in the 4000 year

**Comment by monkey1101luffy** [comment]
we are the most competent country in the world for most of our history

**Comment by monkey1101luffy** [comment]
How do you think about this?

**Comment by monkey1101luffy** [comment]
If the people will just let the governor do bad, there will be no China today.

**Comment by monkey1101luffy** [comment]
We must have been destroyed several times

**Comment by cirosantilli** [comment]
Sorry, I'm not too convinced... china was a superpower in the 19th century, but it has lagged way behind the US, Europe and Japan recently, most likely because of the communists?

**Comment by cirosantilli** [comment]
Look at Japan, Taiwan, South Korea who became capitalists.

**Comment by monkey1101luffy** [comment]
Communist in China started in 1920s I believe

**Comment by monkey1101luffy** [comment]
in the 19th century, China is in Qing Dynasty http://en.wikipedia.org/wiki/Dynasties_in_Chinese_history

**Comment by monkey1101luffy** [comment]
After Qing Dynasty, its Republic of China 1912–1949, which is currently the Taiwan gov

**Comment by cirosantilli** [comment]
I know those dates more or less ~~ What do you mean?

**Comment by monkey1101luffy** [comment]
and I don't want say much here, but the Republic of China is capitalist gov, and they failed because people do not support them

**Comment by monkey1101luffy** [comment]
So same will happen to the current gov in China, which is communist.

**Comment by monkey1101luffy** [comment]
I never worried about this, I will go back to China and fight if the gov is bad

**Comment by monkey1101luffy** [comment]
So "The question is: what if the party does something bad." The answer is clear, we beat them, as we always did

**Comment by monkey1101luffy** [comment]
The question is in fact better phrased "what if the party is not so bad that people will just tolerant?"

**Comment by monkey1101luffy** [comment]
Ok, I agree this is closer to the fact in China. The gov, did something good and also something bad in the past 60 years.

**Comment by monkey1101luffy** [comment]
How good is it? Judge it from the development of China today.

**Comment by monkey1101luffy** [comment]
How bad is it? It has no good comparison, because we only have one gov since the country is built

**Comment by cirosantilli** [comment]
I agree economy is good now. But the reason is that it was way too bad because of Mao's crazy policies in the 60s, so it's easy to improve.

**Comment by cirosantilli** [comment]
My main question is: do you really need to put people in jail to have stability? Democracies are stable.

**Comment by cirosantilli** [comment]
In democracies, we don't have to tolerate good enough: we can choose what we think is the best.

**Comment by monkey1101luffy** [comment]
Wow..I cannot agree, I personally dislike Mao but it is not easy to make such a huge country become one like today's.

**Comment by monkey1101luffy** [comment]
Back to your current question, " do you really need to put people in jail to have stability? Democracies are stable."

**Comment by monkey1101luffy** [comment]
Do you really think so?

**Comment by monkey1101luffy** [comment]
How about the US did?

**Comment by monkey1101luffy** [comment]
THe NSA did?

**Comment by cirosantilli** [comment]
Yes, but at least the people can fight back i ntheir case.

**Comment by monkey1101luffy** [comment]
Why Snowden is out there in Russia

**Comment by cirosantilli** [comment]
They vote for different laws

**Comment by monkey1101luffy** [comment]
How about Julian Assange

**Comment by monkey1101luffy** [comment]
wait a sec, we vote for different laws also

**Comment by cirosantilli** [comment]
In china no one can say anything, not even vote for better laws, so surveillance is even stricter.

**Comment by cirosantilli** [comment]
Ah, how?

**Comment by monkey1101luffy** [comment]
via a comparable policy like the one in the US.

**Comment by monkey1101luffy** [comment]
the problem is it is not well-executed

**Comment by monkey1101luffy** [comment]
but the truth is, it exists

**Comment by cirosantilli** [comment]
Why is it not well executed? How to do it without voting?

**Comment by monkey1101luffy** [comment]
I won't explain it since the policy is complicated, I agree with you that it seems like we are not voting

**Comment by monkey1101luffy** [comment]
But the truth is everybody can vote, its just not so clear

**Comment by cirosantilli** [comment]
Why not make it clearer then?

**Comment by monkey1101luffy** [comment]
Let's narrow it down here, are we talking about vote for gov or law?

**Comment by monkey1101luffy** [comment]
if it is voting for gov, the reason is simple, the gov is unique since we have only one politic party

**Comment by monkey1101luffy** [comment]
if the US only have one politic party, there will be no voting acitivity

**Comment by monkey1101luffy** [comment]
if we are talking about voting for laws

**Comment by cirosantilli** [comment]
agree, in democracies we choose people, and they vote for laws mostly

**Comment by cirosantilli** [comment]
but if they vote for laws we don't like, we don't vote for them anymore

**Comment by cirosantilli** [comment]
so the question comes down to why havea single party?

**Comment by monkey1101luffy** [comment]
truth are: 1. people are chose to vote for law, 2. law are in fact voted up or down by those chosen guys.

**Comment by monkey1101luffy** [comment]
OK, if this is the question, "so the question comes down to why havea single party?" then, I would say, that is historic issue

**Comment by monkey1101luffy** [comment]
why the USA only have two major parties

**Comment by cirosantilli** [comment]
what I mean is

**Comment by monkey1101luffy** [comment]
why the UK only have two major parties, plus a much smaller one

**Comment by cirosantilli** [comment]
why enforce a single party

**Comment by cirosantilli** [comment]
by putting other parties in jail

**Comment by monkey1101luffy** [comment]
OK, so you agrees, one party or two party is not your core concerns, right?

**Comment by cirosantilli** [comment]
yes, I'm talking about suppressing other parties with force

**Comment by monkey1101luffy** [comment]
the problem is why China gov put the other party, usually some one who appears hating the gov, into jail, right?

**Comment by monkey1101luffy** [comment]
or could be more specific

**Comment by monkey1101luffy** [comment]
falun gong followers to jail?

**Comment by cirosantilli** [comment]
thats just one example

**Comment by cirosantilli** [comment]
same goes for tian an men protesters

**Comment by monkey1101luffy** [comment]
Ha

**Comment by cirosantilli** [comment]
or anyone who says anything bad about the government

**Comment by monkey1101luffy** [comment]
for tian an men protesters

**Comment by monkey1101luffy** [comment]
let me tell you something

**Comment by monkey1101luffy** [comment]
I have checked with many people, my parents, their college peers, their colleagues, my college/high school prof/teachers

**Comment by monkey1101luffy** [comment]
those are all the real participants in the 64 student even

**Comment by monkey1101luffy** [comment]
What did I say? I said I dislike the gov's action in that event, and I would like send my support every year in June 4th.

**Comment by monkey1101luffy** [comment]
What did they respond? most often, they are awkward, and then tell me they felt they are immature at that age

**Comment by monkey1101luffy** [comment]
I replied, immature does not mean you cannot did something great

**Comment by monkey1101luffy** [comment]
but then it becomes more awkward, and they will give differnent answers

**Comment by cirosantilli** [comment]
e.g. ?

**Comment by monkey1101luffy** [comment]
one thing similar is that they are regretful, and they dislike those student leaders in that event, those leaders are called braggers

**Comment by cirosantilli** [comment]
ok, so what should the government do about those who want to vote?

**Comment by monkey1101luffy** [comment]
64 event is before I was born, I have limited resource about what the real truth is, and I believe you, and most foreigners won't know much about the real truth. I even doubt how the truth is in my parents and their peers's eyes.

**Comment by monkey1101luffy** [comment]
just one thing I believe, young students has never been able to govern a country successfully

**Comment by monkey1101luffy** [comment]
anyway. what should the government do about those who want to vote?
simple, give them their deserved rights

**Comment by monkey1101luffy** [comment]
that's what I and my peers are expecting

**Comment by cirosantilli** [comment]
expecting to become a democracy?

**Comment by monkey1101luffy** [comment]
sure

**Comment by cirosantilli** [comment]
ok, so when are you going to start saying it?

**Comment by monkey1101luffy** [comment]
I know it is hard for you to understand.

**Comment by monkey1101luffy** [comment]
but the truth is, this is how China is changing itself. The gov's highest leaders, the presidents and governors, of the last ten years and this decades, have given out enough signal that China will/is starting its politic reform

**Comment by monkey1101luffy** [comment]
as a Chinese, I have witnessed and experienced things are changing

**Comment by monkey1101luffy** [comment]
e.g.

**Comment by monkey1101luffy** [comment]
1. there are voting for community leaders, county leaders, just like the one what you are expecting

**Comment by monkey1101luffy** [comment]
2. there are protests for PX factory, for gov's bad policies, just like those in western countries

**Comment by monkey1101luffy** [comment]
3. there started to emerge lots of discussion in China's websites about the civil servant's responsibility, salary, how they should be restricted for less power...

**Comment by cirosantilli** [comment]
that's great

**Comment by cirosantilli** [comment]
so we agree that it is better to be a democracy

**Comment by monkey1101luffy** [comment]
I would say better to have some revised democracy

**Comment by monkey1101luffy** [comment]
the democracy in the US or in UK or else are not perfect

**Comment by monkey1101luffy** [comment]
are not suitable for China, I am expecting something suitable, well-designed for current China

**Comment by monkey1101luffy** [comment]
just like the founders of the US won't copy everything from the europe

**Comment by cirosantilli** [comment]
no govt is perfect. Revised how?

**Comment by monkey1101luffy** [comment]
and they just build something they thought was the best for the US, and during the past 200+ years, it has be revised many times under the framework

**Comment by monkey1101luffy** [comment]
this should be the same for China

**Comment by monkey1101luffy** [comment]
China is a complicated country, Chinese are more like Japanese. And look what Japanese say about their politics.

**Comment by cirosantilli** [comment]
I know nothing about Japan :-(

**Comment by cirosantilli** [comment]
revised how?

**Comment by cirosantilli** [comment]
and when will people be able to say what they think in public? why not today?

**Comment by monkey1101luffy** [comment]
I would say, if you go back to the early 20th century USA, and found how the US treated the Black, and the other minorities like the asians,  you would know thing need time to change

**Comment by monkey1101luffy** [comment]
thousands of people was killed in the USA for that, and people seemed to have no problem with that today.

**Comment by monkey1101luffy** [comment]
it's similar for China, give it 20 years and back to see what had happened

**Comment by monkey1101luffy** [comment]
"when will people be able to say what they think in public? why not today?"
as I clarified, people are free to say anything in the public, just do not do something harm the society

**Comment by cirosantilli** [comment]
of course, I mean things that "harm society" == anything bad about the government which includes bad things the goverment may do

**Comment by monkey1101luffy** [comment]
"I mean things that "harm society" == anything bad about the government which includes bad things the goverment may do"

**Comment by monkey1101luffy** [comment]
I disagree here

**Comment by monkey1101luffy** [comment]
anything bad about the government which includes bad things the goverment may do is not harm the society, you won't get arrested if you say that in the public in China

**Comment by monkey1101luffy** [comment]
there was a certain period, before 1980s, it was true that you will get arrested

**Comment by monkey1101luffy** [comment]
but for today, I readlly doubt that someone will just get arrested for this

**Comment by monkey1101luffy** [comment]
I never keep myself silent when I found the gov is stupid, I say anywhere I want

**Comment by cirosantilli** [comment]
the problem is: who decides what harms society? The government iself. Then if you say: I want to vote, the goverment may say: nope, that disrupts society. Then they put you in jail?

**Comment by cirosantilli** [comment]
Or can you say that in China today?

**Comment by monkey1101luffy** [comment]
Some e.g. that harm the society and def to be arrested
1. terrorist
2. self-killing, like burn him/herself
3.want to overthrow the gov

**Comment by cirosantilli** [comment]
1. and 2. agree

**Comment by cirosantilli** [comment]
3. can include anything bad you say about the gvt, even if true

**Comment by cirosantilli** [comment]
e.g.: it would be better if we were a democracy.

**Comment by monkey1101luffy** [comment]
but if you just want to judge some policy peacefully, no one should be arrested for that

**Comment by monkey1101luffy** [comment]
and it actualy won't happen in China's top cities, if you have problem with gov, go speak it out, in anywhere you like

**Comment by cirosantilli** [comment]
OK, so you say that today you can go on the street and say to everyone: hey, I want to vote, don't you?

**Comment by monkey1101luffy** [comment]
sure

**Comment by cirosantilli** [comment]
ideas always come before actions: anything you say incentivates action

**Comment by monkey1101luffy** [comment]
As far as I know in the most developed areas, the top 20 cities, there is barely any difference from the western world

**Comment by cirosantilli** [comment]
I dare you to go to the street in beijing, with a note saying that, take a selfie and send it to me :-)

**Comment by cirosantilli** [comment]
and what about blogs: if you put on a blog: I WANT DEMOCRACY, then the blog won't be taken down?

**Comment by monkey1101luffy** [comment]
but for the rural areas, less developed cities, I admit there might be such issues

**Comment by monkey1101luffy** [comment]
no it won't

**Comment by monkey1101luffy** [comment]
check this http://dig.chouti.com/

**Comment by monkey1101luffy** [comment]
this is a website in China, with most users are discuss the "stupid" gov and policies

**Comment by cirosantilli** [comment]
that is good to know

**Comment by monkey1101luffy** [comment]
no one get arrested or blocked for such behavior

**Comment by cirosantilli** [comment]
OK, I will try that out myself!

**Comment by monkey1101luffy** [comment]
but there is one thing ugly with China's gov and internet

**Comment by monkey1101luffy** [comment]
that is as you know, some of the words are blocked, like tian an men square even and it's variants

**Comment by monkey1101luffy** [comment]
and your post will get blocked for containing these words

**Comment by monkey1101luffy** [comment]
and facebook and twitter, etc. are blocked for the same reason

**Comment by cirosantilli** [comment]
you think that is good or bad?

**Comment by monkey1101luffy** [comment]
definitely stupid, but I cannot say if it is good or bad

**Comment by cirosantilli** [comment]
great.

**Comment by cirosantilli** [comment]
let's make a test: we decide on the messages we will post, and post them, and see if they get blocked.

**Comment by cirosantilli** [comment]
How about: "Dear government, please let us vote directly for president. I promise I won't start a revolution if you don't let me".

**Comment by monkey1101luffy** [comment]
haha you might be too obvious that you are trying to do a revolution by saying this

**Comment by cirosantilli** [comment]
But thats the problem: anything bad you say about the gvt disrupts it and increases the probability or revolution

**Comment by monkey1101luffy** [comment]
instead, if it was me, I will say "dear gov, please listen to the voice of people, we believe we have the right to vote(maybe indirectly as they do in the US)"

**Comment by monkey1101luffy** [comment]
you won't get blocked

**Comment by cirosantilli** [comment]
that's too indirect for my taste :-(

**Comment by cirosantilli** [comment]
any dictatorship can "listen" to people

**Comment by monkey1101luffy** [comment]
then just say "ear gov,we believe we have the right to vote(maybe indirectly as they do in the US)"

**Comment by monkey1101luffy** [comment]
that is also fine

**Comment by monkey1101luffy** [comment]
as I said, the only problem is some words, just avoid them

**Comment by monkey1101luffy** [comment]
revolution may be one of the work make your post potentially be blocked, I will suggest just avoid using it

**Comment by monkey1101luffy** [comment]
otherwise just fine

**Comment by cirosantilli** [comment]
OK. Can we remove the "(maybe indirectly as they do in the US)" ?

**Comment by monkey1101luffy** [comment]
I think so

**Comment by monkey1101luffy** [comment]
as I said, the only problem is those sensitive words

**Comment by cirosantilli** [comment]
OK! Awesome! We could also make a list of stuff that gets blocked and stuff that does not and add it to a repo on github.

**Comment by cirosantilli** [comment]
Fine, we will avoid those for now. But we agree that it would be better that no word be forbidden?

**Comment by monkey1101luffy** [comment]
you know data mining, the gov just believe if you are using those sensitive words, then you are more like a "bad guy"

**Comment by cirosantilli** [comment]
we post each message under a different account

**Comment by monkey1101luffy** [comment]
I cannot say if it will be better, I just agree that this behavior is stupid

**Comment by monkey1101luffy** [comment]
You can posted it as you like, I will just follow the result

**Comment by cirosantilli** [comment]
OK. We also need a list of target websites. The larger the better. I can look at the Alexa top 100 in china in which we can post messages.

**Comment by monkey1101luffy** [comment]
if you like, I can translate it for you.

**Comment by monkey1101luffy** [comment]
Ok, sina.com.cn, 163.com.cn are the biggest

**Comment by cirosantilli** [comment]
Great, I have to sleep now, when I get some more free time I will give it a shot and report back here.

**Comment by cirosantilli** [comment]
You can propose a translation for "Dear gov, please let us vote for president?"

**Comment by cirosantilli** [comment]
And I liked talking to you monkey. I hope china keeps improving in all senses. Cheers.

**Comment by monkey1101luffy** [comment]
I suggested you comment in any news on those website, rather than write a single thread of post, it will be too obvious if you just write a post containing "亲爱的政府，请让我们拥有选举领导人的权利"

**Comment by monkey1101luffy** [comment]
anyway, do it, let me know the result

**Comment by monkey1101luffy** [comment]
Hi, this will be the final post of Monkey.
