### ISSUE TITLE
How to check if your method of provoking GFW is working?

### ISSUE THREAD

**Issue by janot** [cirosantilli/chat#22]
From this 2 services it looks like your profile page on stackoverflow is accessible from China. Is there better way to check? I mean except asking somebody from China.

https://en.greatfire.org/https/stackoverflow.com/users/895245/ciro-santilli-%E5%B7%B4%E6%8B%BF%E9%A6%AC%E6%96%87%E4%BB%B6-%E5%85%AD%E5%9B%9B%E4%BA%8B%E4%BB%B6-%E6%B3%95%E8%BD%AE%E5%8A%9F

http://www.websitepulse.com/tests/ed5c31a4d728af15.html#China firewall/https%3A%2F%2Fstackoverflow.com%2Fusers%2F895245%2Fciro-santilli-%25E5%25B7%25B4%25E6%258B%25BF%25E9%25A6%25AC%25E6%2596%2587%25E4%25BB%25B6-%25E5%2585%25AD%25E5%259B%259B%25E4%25BA%258B%25E4%25BB%25B6-%25E6%25B3%2595%25E8%25BD%25AE%25E5%258A%259F

**Comment by cirosantilli** [comment]
I don't know better methods than those sites like greatfire.

Just make sure you use `http` instead of `https`: it is impossible to selectively block `https` pages since they are encrypted, you have to take down the whole domain.

I think I haven't activated the GFW yet ;-)

**Comment by janot** [comment]
Yep, forgot about `https` thing.
